---
title: "final_project"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
usm_hispanic_by_gender <- read_csv("https://raw.githubusercontent.com/emely-miranda/jour405_spring25/refs/heads/main/project/USM_HISPANIC_ENROLLMENT_GENDER.csv")
```

```{r}
usm_hispanic_enrollment <- read_csv("https://raw.githubusercontent.com/emely-miranda/jour405_spring25/refs/heads/main/project/USM_HISPANIC_ENROLLMENT.csv")
```
##How do I get each year, 2015-2023, to appear on the x-axis?
USM HISPANIC ENROLLMENT:
```{r}
yearly_totals <- usm_hispanic_enrollment |>
  group_by(year) |>
  summarize(total = sum(enrollment)) |> 
  mutate(numeric_year = as.numeric(substr(year, 3, 4)) + 2000)

yearly_totals |>
  ggplot(aes(x = numeric_year, y = total)) +
  geom_point() +
  geom_smooth(method = "lm", color = "seagreen") +
  labs(x= "Academic Semester", y = "Enrollment", title = "USM Enrollment of Hispanic Students")
```


```{r}
model = lm(total ~ numeric_year, data = yearly_totals)
summary(model)
```


USM HISPANIC ENROLLMENT BY GENDER:
```{r}
usm_hispanic_by_gender |> summarize(correlation = cor(Male, Female, method = "pearson"))
```
```{r}
usm_hispanic_by_gender |> 
  ggplot() + 
  geom_point(aes(x=Male, y = Female)) +
    geom_smooth(aes(x = Male, y = Female), method = "lm", color = "seagreen") +
  labs(title = "USM Male and Female Hispanic Enrollment")
```

```{r}
usm_hispanic_by_gender <- usm_hispanic_by_gender |>
  arrange(Year) |>
  mutate(
    male_change = Male - lag(Male),
    male_pct_change = (Male - lag(Male))/lag(Male) * 100,
    female_change = Female - lag(Female),
    female_pct_change = (Female - lag(Female))/lag(Female) * 100)

t_test_result <- t.test (
  usm_hispanic_by_gender$male_pct_change,
  usm_hispanic_by_gender$female_pct_change,
  paired = TRUE
)

t_test_result
```

```{r}
usm_hispanic_by_gender <- usm_hispanic_by_gender |>
  group_by(Year) |>
  mutate(numeric_year = as.numeric(substr(Year, 3, 4)) + 2000)

male_model <- lm(Male ~ numeric_year, data = usm_hispanic_by_gender)
summary (male_model)
```
```{r}
female_model <- lm(Female ~ numeric_year, data = usm_hispanic_by_gender)
summary (female_model)
```

```{r}
institution_enrollment <- usm_hispanic_enrollment |>
  mutate(numeric_year = as.numeric(substr(year, 3, 4)) + 2000) |> 
  arrange(school, numeric_year) |> 
  group_by(school) |> 
  mutate(pct_change = (enrollment - lag(enrollment)) / lag(enrollment) * 100)

anova_result <- aov(pct_change ~ school, data = institution_enrollment)
summary(anova_result)
```

